language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - python setup.py install

# command to run tests
script:
    - pip install -r test-requirements.txt
    - ipcluster start -n 2 &
    - nosetests -v parsl/tests/test_threads
    - sleep 60
    - nosetests -v parsl/tests/test_ipp
    - ipcluster stop
