language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - python setup.py install

# command to run tests
script:
    - pip install -r test-requirements.txt
    - nosetests -v parsl/tests